namespace BackTesting.Model.Strategies
{
    /// <summary>
    /// Strategy is an abstract base class providing an interface for
    /// all subsequent (inherited) strategy handling objects.
    /// 
    /// The goal of a (derived) Strategy object is to generate Signal
    /// objects for particular symbols based on the inputs of Bars 
    /// (OLHCVI) generated by a DataHandler object.
    /// 
    /// This is designed to work both with historic and live data as
    /// the Strategy object is agnostic to the data source,
    /// since it obtains the bar tuples from a queue object.
    /// </summary>
    public interface IStrategy
    {
        /// <summary>
        /// Provides the mechanisms to calculate the list of signals.
        /// </summary>
        void CalculateSignals();
    }
}
